site_name: textforge
site_url: https://ameen-91.github.io/textforge/
nav:
    - Home: index.md
    - How to with a Local LLM: how_to_local.md
    - Pipeline: pipeline.md
    - Synthetic Data Generation: synthetic_data.md
    - Training: training.md
    - Quantization: quantization.md
    - Deployment: deployment.md
repo_url: https://github.com/ameen-91/textforge/
repo_name: ameen-91/textforge

theme:
    name: material
    features:
        - content.code.copy
        - content.code.select
    palette:
        primary: black
        accent: indigo
    version:
        provider: poetry
        package: textforge
plugins:
    - mkdocstrings:
        handlers:
            python:
                options:
                    show_inheritance_diagram: true
                    allow_inspection: true
    - social:
        enabled: !ENV [CI, false]
        cards: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences